# Ex1 - Filtering and Sorting Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

### Step 3. Assign it to a variable called chipo.

In [113]:
url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv'
chipo = pd.read_csv(url, sep='\t')

In [114]:
chipo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
order_id              4622 non-null int64
quantity              4622 non-null int64
item_name             4622 non-null object
choice_description    3376 non-null object
item_price            4622 non-null object
dtypes: int64(2), object(3)
memory usage: 180.6+ KB

### Step 4. How many products cost more than $10.00?

In [115]:
chipo.item_price = chipo.item_price.map(lambda x: x.lstrip('$'))
chipo.item_price = chipo.item_price.astype('float64')

In [116]:
len(chipo[chipo.item_price > 10])

1130

### Step 5. What is the price of each item? 
###### print a data frame with only two columns item_name and item_price

In [126]:
filtered = chipo.drop_duplicates(['item_name', 'item_price'])
pricePerItem = filtered[filtered.quantity == 1]
sortedItems = pricePerItem.sort_values(by='item_price')
sortedItems

,order_id,quantity,item_name,choice_description,item_price
34,17,1,Bottled Water,NaN,1.09
28,14,1,Canned Soda,[Dr. Pepper],1.09
263,114,1,Canned Soft Drink,[Coke],1.25
329,143,1,Bottled Water,NaN,1.50
6,3,1,Side of Chips,NaN,1.69
4509,1793,1,Chips,NaN,1.99
40,19,1,Chips,NaN,2.15
730,301,1,Chips and Fresh Tomato Salsa,NaN,2.29
191,85,1,Chips and Roasted Chili-Corn Salsa,NaN,2.39
300,130,1,Chips and Tomatillo-Red Chili Salsa,NaN,2.39
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
111,49,1,Chips and Tomatillo Red Chili Salsa,NaN,2.95
89,39,1,Chips and Fresh Tomato Salsa,NaN,2.95
233,102,1,Chips and Roasted Chili Corn Salsa,NaN,2.95
38,18,1,Chips and Tomatillo Green Chili Salsa,NaN,2.95
674,279,1,Chips and Mild Fresh Tomato Salsa,NaN,3.00
2,1,1,Nantucket Nectar,[Apple],3.39
1,1,1,Izze,[Clementine],3.39
927,382,1,Chips and Guacamole,NaN,3.89
49,22,1,Chips and Guacamole,NaN,3.99
676,279,1,Chips and Guacamole,NaN,4.00
10,5,1,Chips and Guacamole,NaN,4.45
298,129,1,6 Pack Soft Drink,[Sprite],6.49
1414,575,1,Salad,"[Brown Rice, Adobo-Marinated and Grilled Chick...",7.40
510,214,1,Burrito,"[Adobo-Marinated and Grilled Chicken, Pinto Be...",7.40
520,217,1,Crispy Tacos,[Adobo-Marinated and Grilled Steak],7.40
673,279,1,Bowl,"[Adobo-Marinated and Grilled Steak, [Sour Crea...",7.40
1161,479,1,Chicken Burrito,"[Fresh Tomato (Mild), [Lettuce, Rice, Fajita V...",8.19
3989,1598,1,Chicken Salad,"[Roasted Chili Corn (Medium), [Lettuce, Black ...",8.19
...,...,...,...,...,...
57,26,1,Veggie Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.25
62,28,1,Veggie Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
738,304,1,Veggie Soft Tacos,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.25
13,7,1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
1189,488,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
3276,1313,1,Barbacoa Burrito,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",11.48
163,74,1,Carnitas Bowl,"[Roasted Chili Corn Salsa (Medium), [Pinto Bea...",11.48
471,202,1,Barbacoa Bowl,"[[Tomatillo-Green Chili Salsa (Medium), Roaste...",11.48
429,186,1,Barbacoa Crispy Tacos,"[[Roasted Chili Corn Salsa (Medium), Tomatillo...",11.48
187,84,1,Steak Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Fajita Vegg...",11.48
1063,438,1,Carnitas Burrito,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",11.48
1721,694,1,Steak Soft Tacos,"[[Fresh Tomato Salsa (Mild), Tomatillo-Red Chi...",11.48
3184,1273,1,Barbacoa Soft Tacos,"[Tomatillo-Red Chili Salsa (Hot), [Rice, Chees...",11.48
147,66,1,Steak Burrito,"[Tomatillo-Green Chili Salsa (Medium), [Rice, ...",11.48
4510,1793,1,Barbacoa Bowl,[Guacamole],11.49
1963,793,1,Carnitas Soft Tacos,"[Fresh Tomato Salsa, [Sour Cream, Guacamole]]",11.75
130,57,1,Barbacoa Burrito,"[Roasted Chili Corn Salsa, [Rice, Pinto Beans,...",11.75
97,43,1,Carnitas Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.75
93,41,1,Carnitas Burrito,"[Roasted Chili Corn Salsa, [Sour Cream, Guacam...",11.75
90,40,1,Steak Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",11.75
988,406,1,Barbacoa Soft Tacos,"[Tomatillo Red Chili Salsa, [Black Beans, Chee...",11.75
168,75,1,Barbacoa Crispy Tacos,"[Tomatillo Red Chili Salsa, [Rice, Black Beans...",11.75
1353,552,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Fajita Vegetabl...",11.75
39,19,1,Barbacoa Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",11.75
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.75
2231,899,1,Steak Crispy Tacos,"[Fresh Tomato Salsa, Guacamole]",11.75
1008,413,1,Carnitas Crispy Tacos,"[Tomatillo Green Chili Salsa, [Rice, Black Bea...",11.75
1229,501,1,Barbacoa Salad Bowl,"[Fresh Tomato Salsa, [Rice, Fajita Vegetables,...",11.89
606,250,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Pinto Beans, Cheese, Gua...",11.89
1132,468,1,Carnitas Salad Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",11.89

### Step 6. Sort by the name of the item

In [118]:
chipo.sort_values(by='item_name').head()

      order_id  quantity          item_name choice_description  item_price
3389      1360         2  6 Pack Soft Drink        [Diet Coke]       12.98
341        148         1  6 Pack Soft Drink        [Diet Coke]        6.49
1849       749         1  6 Pack Soft Drink             [Coke]        6.49
1860       754         1  6 Pack Soft Drink        [Diet Coke]        6.49
2713      1076         1  6 Pack Soft Drink             [Coke]        6.49

In [129]:
chipo.item_name.sort_values()

3389    6 Pack Soft Drink
341     6 Pack Soft Drink
1849    6 Pack Soft Drink
1860    6 Pack Soft Drink
2713    6 Pack Soft Drink
3422    6 Pack Soft Drink
553     6 Pack Soft Drink
1916    6 Pack Soft Drink
1922    6 Pack Soft Drink
1937    6 Pack Soft Drink
3836    6 Pack Soft Drink
298     6 Pack Soft Drink
1976    6 Pack Soft Drink
1167    6 Pack Soft Drink
3875    6 Pack Soft Drink
1124    6 Pack Soft Drink
3886    6 Pack Soft Drink
2108    6 Pack Soft Drink
3010    6 Pack Soft Drink
4535    6 Pack Soft Drink
4169    6 Pack Soft Drink
4174    6 Pack Soft Drink
4527    6 Pack Soft Drink
4522    6 Pack Soft Drink
3806    6 Pack Soft Drink
2389    6 Pack Soft Drink
3132    6 Pack Soft Drink
3141    6 Pack Soft Drink
639     6 Pack Soft Drink
1026    6 Pack Soft Drink
              ...
2996         Veggie Salad
3163         Veggie Salad
4084         Veggie Salad
1694         Veggie Salad
2756         Veggie Salad
4201    Veggie Salad Bowl
1884    Veggie Salad Bowl
455     Veggie Salad Bowl
3223    Veggie Salad Bowl
2223    Veggie Salad Bowl
2269    Veggie Salad Bowl
4541    Veggie Salad Bowl
3293    Veggie Salad Bowl
186     Veggie Salad Bowl
960     Veggie Salad Bowl
1316    Veggie Salad Bowl
2156    Veggie Salad Bowl
4261    Veggie Salad Bowl
295     Veggie Salad Bowl
4573    Veggie Salad Bowl
2683    Veggie Salad Bowl
496     Veggie Salad Bowl
4109    Veggie Salad Bowl
738     Veggie Soft Tacos
3889    Veggie Soft Tacos
2384    Veggie Soft Tacos
781     Veggie Soft Tacos
2851    Veggie Soft Tacos
1699    Veggie Soft Tacos
1395    Veggie Soft Tacos
Name: item_name, dtype: object

### Step 7. What was the quantity of the most expensive item ordered?

In [119]:
item = chipo['item_price'].max()
chipo[chipo.item_price == item]

,order_id,quantity,item_name,choice_description,item_price
3598,1443,15,Chips and Fresh Tomato Salsa,NaN,44.25

In [132]:
chipo.sort_values(by='item_price', ascending=False).head(1)

,order_id,quantity,item_name,choice_description,item_price
3598,1443,15,Chips and Fresh Tomato Salsa,NaN,44.25

### Step 8. How many times were a Veggie Salad Bowl ordered?

In [120]:
len(chipo[chipo.item_name == 'Veggie Salad Bowl'])

18

### Step 9. How many times people orderd more than one Canned Soda?

In [121]:
len(chipo[(chipo.item_name == 'Canned Soda') & (chipo.quantity > 1)])

20